"""empty message

Revision ID: 0b0f8ec13862
Revises: 09e68341edfc
Create Date: 2016-07-18 19:02:14.211423

"""

# revision identifiers, used by Alembic.
revision = '0b0f8ec13862'
down_revision = '09e68341edfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('sticker', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('dRangeFrom', sa.Integer(), nullable=True),
    sa.Column('dRangeUntil', sa.Integer(), nullable=True),
    sa.Column('weekdays', sa.Text(), nullable=True),
    sa.Column('tRangeFrom', sa.Integer(), nullable=True),
    sa.Column('tRangeUntil', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('google_users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('google_users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_users', 'date_modified')
    op.drop_column('google_users', 'date_created')
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_table('conversations')
    ### end Alembic commands ###
