"""empty message

Revision ID: ca8cff12ffd6
Revises: None
Create Date: 2016-07-20 15:24:03.501127

"""

# revision identifiers, used by Alembic.
revision = 'ca8cff12ffd6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('verified_email', sa.Boolean(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('dateRangeFrom', sa.Integer(), nullable=True),
    sa.Column('dateRangeUntil', sa.Integer(), nullable=True),
    sa.Column('weekdaysMon', sa.Boolean(), nullable=True),
    sa.Column('weekdaysTues', sa.Boolean(), nullable=True),
    sa.Column('weekdaysWed', sa.Boolean(), nullable=True),
    sa.Column('weekdaysThurs', sa.Boolean(), nullable=True),
    sa.Column('weekdaysFri', sa.Boolean(), nullable=True),
    sa.Column('weekdaysSat', sa.Boolean(), nullable=True),
    sa.Column('weekdaysSun', sa.Boolean(), nullable=True),
    sa.Column('timeRangeFrom', sa.Integer(), nullable=True),
    sa.Column('timeRangeUntil', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('google_users')
    ### end Alembic commands ###
