"""empty message

Revision ID: d15f970537db
Revises: 09e68341edfc
Create Date: 2016-07-15 20:18:11.640834

"""

# revision identifiers, used by Alembic.
revision = 'd15f970537db'
down_revision = '09e68341edfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sticker', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['google_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['google_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_table('conversations')
    ### end Alembic commands ###
